### ISSUE TITLE
Add `www` on sites that need it

### ISSUE THREAD

**Issue by konklone** [GSA/analytics.usa.gov#140]
Google Analytics strips the `www` off of domains before they give us the URL, which is maddening. 

For example, [this Nimoy tribute](http://www.nasa.gov/content/astronaut-salutes-nimoy-from-orbit/#.VPN3JXXN-Wg) was in the Top 20 for a time:

> http://www.nasa.gov/content/astronaut-salutes-nimoy-from-orbit/#.VPN3JXXN-Wg

But the link broke, because NASA doesn't redirect `nasa.gov` to `www.nasa.gov`. This fails to connect:

> http://nasa.gov/content/astronaut-salutes-nimoy-from-orbit/#.VPN3JXXN-Wg

This is in clear tension with my position in #139, but I'm in support of making exceptions here for 3 reasons, in no particular order:

* Changing server/DNS setup is generally more difficult than changing `<title>` tags.
* We would only do this for a set of second-level domains, not subdomains, so there's a very finite set of things we'd have to make exceptions for.
* This is fundamentally Google's fault.

cc @tdlowden @gbinal

**Comment by gbinal** [comment]
NASA's absurd failure to address their `www` issue aside, I agree with this move.

**Comment by tdlowden** [comment]
Does this, in a way, absolve agencies from not following best practices? FWIW, I have no issue saying "we don't make the websites, the agency can fix that issue at their discretion".

**Comment by konklone** [comment]
Yes, it does absolve agencies from following best practices. I'm okay patching it, but if you wanted to send this down the line to agencies, there'd be a lot of good to that too. I also think it's annoying that Google is chopping off the `www`.

**Comment by konklone** [comment]
Closing in favor of https://github.com/GSA/DAP-Gov-wide-GA-Code/issues/10, and any other one-off exceptions needed along the way.

**Comment by danhammer** [comment]
Note that [nasa.gov](http://nasa.gov) now resolves.

**Comment by konklone** [comment]
We never ended up special-casing nasa.gov in the JavaScript code here, the links stayed broken -- and now they work! Thanks again, @danhammer!
