### ISSUE TITLE
Broken Link 

### ISSUE THREAD

**Issue by wslack** [GSA/analytics.usa.gov#147]
Under "About This Site:"

"Not every government website is represented in this data. Currently, the Digital Analytics Program collects web traffic from almost 300 executive branch government domains, including every cabinet department, [out of about 1,350 domains](https://catalog.data.gov/dataset/gov-domains-api) total. We continue to pursue and add more sites frequently; to add your site, email the Digital Analytics Program."

**Comment by wslack** [comment]
Maybe it should point [here](https://catalog.data.gov/dataset/federal-executive-agencies-domain-list), but that link doesn't work either at the moment. You can find a working excel link [here](https://catalog.data.gov/dataset?q=domains&sort=score+desc%2C+name+asc), but it doesn't seem permanent.

**Comment by konklone** [comment]
Fixed in https://github.com/GSA/analytics.usa.gov/commit/8eb7724092a3cc04d17844600f6e3069c10362c4. Should be live in 5 minutes.

**Comment by wslack** [comment]
Fixed
