### ISSUE TITLE
Consider Piwik

### ISSUE THREAD

**Issue by openbrian** [GSA/analytics.usa.gov#156]
I think it's great 18F is "all in" with open source.  Have you considered using Piwik in place of Google Analytics?  It would eliminate request limits.

**Comment by wslack** [comment]
Piwik Commentary on Hacker News [here](https://news.ycombinator.com/item?id=9236294).

**Comment by tdlowden** [comment]
Thanks for this. We will keep Piwik in mind when evaluating tools.
