### ISSUE TITLE
Don't assume gzip capabilities

### ISSUE THREAD

**Issue by cmc333333** [GSA/analytics.usa.gov#157]
Looks like the json files are only available gzipped (even if the request doesn't ask for gzipped data)
```bash
[cmc@fresh tmp]$ curl https://analytics.usa.gov/data/live/top-pages-realtime.json > data.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1269  100  1269    0     0   3660      0 --:--:-- --:--:-- --:--:--  3667
[cmc@fresh tmp]$ file data.json
data.json: gzip compressed data, from Unix
```

Obviously not a high priority.

**Comment by konklone** [comment]
Unfortunately, S3 doesn't support `Vary-Encoding` or any form of dynamic content negotiation. So for a given URL, we just have to decide whether we store it compressed or uncompressed. We chose to store it compressed, which clearly complicates it for the general case.

Perhaps this is a good motivator for a proper data download solution, which would include dated snapshots, that are stored in uncompressed form and not expected to be dynamically loaded by every visitor.
