### ISSUE TITLE
Missing visit time breakdown bargraph

### ISSUE THREAD

**Issue by audiodude** [GSA/analytics.usa.gov#161]
![screen shot 2015-03-19 at 21 37 38](https://cloud.githubusercontent.com/assets/57832/6746124/3a70918e-ce80-11e4-89dd-50f2e967030f.png)

I checked my developer console and didn't see anything in particular amiss.

I also have AdBlock Plus installed, which may be relevant.

Note that I did see the bars the first time I visited the site maybe an hour ago.

**Comment by audiodude** [comment]
I now see:

![screen shot 2015-03-19 at 21 54 40](https://cloud.githubusercontent.com/assets/57832/6746269/9ada9b58-ce82-11e4-8268-dc60a2b952bf.png)

I'm going to go on a limb and suggest this was because it was just after midnight Eastern Time when I looked at this, and so there wasn't enough data to show a bar for 12a-1a yet?

**Comment by cew821** [comment]
Yes, you're right @audiodude -- the chart looks a bit odd at 12am - 1am. I'm going to close this, but feel free to open a new issue for changing this expected behavior. I can imagine some folks might have good ideas for how to avoid this.
