### ISSUE TITLE
Site has bad reputation for Avast Extension

### ISSUE THREAD

**Issue by casivaagustin** [GSA/analytics.usa.gov#167]
Looking into the site with the Avast Extension for chrome I got this message

![screenshot 2015-03-20 16 04 24](https://cloud.githubusercontent.com/assets/673481/6758922/b415d3b0-cf1a-11e4-9a3d-cb2e4694b344.png)

I'll recommend to check blacklist, dns issues, ip blacklisting, possible malware in the server, etc.

**Comment by konklone** [comment]
Thanks, but this isn't actionable as files. If you can point to any specific complaints Avast or any other 3rd party system has with analytics.usa.gov or the domain, please re-open and we'll look into them.

**Comment by gbinal** [comment]
Agreed.  Thanks for the heads up, @casivaagustin and holler if you see anything specific.
