### ISSUE TITLE
nasa.gov does not resolve (top 20 sites in the 30 day list)

### ISSUE THREAD

**Issue by pavgup** [GSA/analytics.usa.gov#171]
I happened to click on the nasa.gov link that is the eigth most frequented site over the previous 30 days.  Unfortunately, the link for nasa.gov points to a domain that does not resolve and, therefore, a link that is not usable.

**Comment by mleibner** [comment]
[nasa.gov](http://nasa.gov) doesn't resolve (no A entry) & seems to require the [www](http://www.nasa.gov) subdomain.

**Comment by konklone** [comment]
NASA is [on-record as not planning to support www](https://blogs.nasa.gov/nasadotgov/2011/05/31/post_1306860816073/). I think this an unwise decision on NASA's part, but we discussed workarounds in https://github.com/GSA/analytics.usa.gov/issues/140, and this has now moved to https://github.com/GSA/DAP-Gov-wide-GA-Code/issues/10.

**Comment by cew821** [comment]
@danhammer: any insight into the above? I bet it would help lots of people (not just analytics.usa.gov) if nasa.gov resolved to www.nasa.gov

**Comment by konklone** [comment]
The primary counter-argument I have to the post is that it says that the missed traffic to `nasa.gov` is both too low to matter much, but so high that they'd have to pay tons of $ to incorporate the redirect into their CDN. I don't think those can both be true. They could try using a cheap, ordinary server to do 301 redirects and see how well it performs. If it ends up choking under the load (which I don't expect it would), it's no worse than the status quo.

**Comment by danhammer** [comment]
@cew821 no insight.  this is a quick ask, though.  more soon (after my honeymoon!!).

**Comment by danhammer** [comment]
@cew821 and @konklone: I spoke to the (embattled) author of the post that Eric was talking about.  He kicked me back down to someone else.  This seems like an eminently reasonable fix (now that I understand the landscape a little more).  More updates soon.

**Comment by gbinal** [comment]
See this get fixed, Dan, and I'm going to name a child after you.

**Comment by danhammer** [comment]
well, @gbinal, look out for little Gray Hammer soon enough.  i spoke with another developer at NASA, and it seems like this could be really simple.  Look:
```bash
computer-rock:api-docs danhammer$ dig data.nasa.gov
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27477
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
;; ANSWER SECTION:
data.nasa.gov.		600	IN	CNAME	open-prod.arc.nasa.gov.
open-prod.arc.nasa.gov.	10930	IN	A	128.102.186.77
```
**versus**
```bash
computer-rock:api-docs danhammer$ dig nasa.gov
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61593
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; AUTHORITY SECTION:
nasa.gov.		121	IN	SOA	nsa2.nasa.gov. dns.nasa.gov. 2008046394 3600 900 1209600 300
```
There may be a way to do this purely by setting an appropriate `CNAME`.  More updates soon.

**Comment by pavgup** [comment]
Before I go racing into RFCs, I should point out that casual nasa.gov users have been duped into thinking the site was down for reasons exclusively related to nasa.gov not resolving (https://gp.gg/4j). It's a painful enough result that users are reporting it somewhat frequently in a totally unrelated, public space.  

That being said, I think NASA might have this one right. At their apex domain (nasa.gov) they're using a slew of records (SOA, NS, DNSSEC, TXT, etc.) and if you take a gander at RFC1912 (https://gp.gg/4k) the NASA seems to be explicitly following the rules laid out in section 2.4 of that RFC.  Here's some easy reading:

>A CNAME record is not allowed to coexist with any other data.  In other words, if suzy.podunk.xx is an alias for sue.podunk.xx, you can't also have an MX record for suzy.podunk.edu, or an A record, or even a TXT record.  Especially do not try to combine CNAMEs and NS records like this!:


>           podunk.xx.      IN      NS      ns1
>                           IN      NS      ns2
>                           IN      CNAME   mary
>           mary            IN      A       1.2.3.4


>This is often attempted by inexperienced administrators as an obvious way to allow your domain name to also be a host.  However, DNS servers like BIND will see the CNAME and refuse to add any other resources for that name.  Since no other records are allowed to coexist with a CNAME, the NS entries are ignored.  Therefore all the hosts in the podunk.xx domain are ignored as well!

>If you want to have your domain also be a host, do the following:

>           podunk.xx.      IN      NS      ns1
>                           IN      NS      ns2
>                           IN      A       1.2.3.4
>           mary            IN      A       1.2.3.4

If you read around the author's context, you get the feeling that February 1996 wasn't a year of abundant DNS resources and both BIND and Penn States' D. Barr were quietly conspiring to be curmudgeons.  Unfortunately, about  year and a half later, Elz and Bush in RFC2181 (http://gp.gg/4l) offer a DNSSEC exception for CNAME records, but, again, clearly disallow the use of nasa.gov's apex record linked to a CNAME record.  Here's the relevant casual reading:

>The DNS CNAME ("canonical name") record exists to provide the canonical name associated with an alias name.  There may be only one such canonical name for any one alias.  That name should generally be a name that exists elsewhere in the DNS, though there are some rare applications for aliases with the accompanying canonical name undefined in the DNS.  An alias name (label of a CNAME record) may, if DNSSEC is in use, have SIG, NXT, and KEY RRs, but may have no other data.  That is, for any label in the DNS (any domain name) exactly one of the following is true:

>     + one CNAME record exists, optionally accompanied by SIG, NXT, and KEY RRs,
>     + one or more records exist, none being CNAME records,
>     + the name exists, but has no associated RRs of any type,
>     + the name does not exist at all.

Honestly, the nasa.gov domain name setup is just, well, messy.  Take for example their casual use case of www.nasa.gov.  It resolves to www.nasawestprime.com (registered on gandi.net with contact details shuttled to the gandi.net's privacy apparatus -- wtf?) and then this hop is resolved to iznasa.hs.llnwd.net (their cdn) which finally reports back an A record pointing to an IP address (208.111.131.86 in my case). I'm sure lots of thought has gone into this, but it certainly seems like a messy DNS arrangement coupled to what seems like a haphazardly installed CDN.  

All that said, I love NASA -- maybe to make their intense DNS zone file make a bit more sense, they should start sharing their nameservers with other agencies or maybe they should use one of the 6 available name servers GSA sports, or they should take a page out of whitehouse.gov's book and start using somewhat more robust services out of somebody like Akamai (or anybody else in that business).

Bah, I was really excited.  NASA is the best and I might have been able to tell my progeny years from now that nasa.gov was repointed thanks to my complaint and everyone's wicked hardwork.  Alas, I feel sunk. :-(

**Comment by pavgup** [comment]
(Whoops, forgot to add, most importantly:) 

There could be a solution where NASA opts to use A records like RFC1912 suggests.  iznasa.hs.llnwd.net is simply returns an A record and nasa.gov could do the same. Every IP that iznasa is willing to offer up should be loadded into place for nasa.gov to offer up. I'm sure there's some special sauce over at iznasa.hs.llnwd.net to cost NASA a pretty penny, but maybe the traffic flow is low enough to nasa.gov to not neccessitate super clever DNS-delivered load balancing.  I'd frankly bet NASA is more likely to make this work than most -- could be a very viable solution.  And RFC-blessed.

**Comment by gbinal** [comment]
> That being said, I think NASA might have this one right.

Totally respecting the expertise in your comments, @pavgup, I have to say that there's no way on God's green earth that it is right for `nasa.gov` not to resolve.  I'm crossing my fingers that I might see a resolution to this episode somehow.

**Comment by danhammer** [comment]
yeah, @pavgup and @gbinal, stay tuned.  the ARC guys seem optimistic.  the blue marble may yet be green.

**Comment by pavgup** [comment]
@gbinal definitely.  Here's to nasa.gov feeling a bit more comfy from the browser -- heck, I think adding the following A/AAAA records to nasa.gov gets you going, albeit without limelight's clearly geographically aware A/AAAA record resolution:  

```
A  68.142.102.212
A  69.28.157.198
A  87.248.214.97
A  111.119.8.38
A  117.121.250.65
A  203.77.187.16
A  208.111.155.209
A  208.111.179.103
```

```
AAAA  2402:6800:711:a000::e
AAAA  2607:f4e8:110:a000::e
AAAA  2607:f4e8:130:a000::e
AAAA  2607:f4e8:310:a000::e
AAAA  2607:f4e8:330:a000::e
AAAA  2a02:3d0:600:a000::e
```

And @danhammer, schweet.  The world becomes just a little bit better.  I like.

**Comment by mleibner** [comment]
If Limelight Networks (the vendor behind llnwd.net) doesn't rotate IPs often, then the solution from @pavgup would probably work for NASA. Even if the IPs do rotate often, I have a hard time believing that Limelight doesn't have some sort of solution for customers who control their own DNS, but still want to use their apex domain.

For what it's worth, a few third-party DNS services services offer alias-type records which effectively offer CNAME-type resolution for apex domains (the CNAME resolution is done on the backend, and then A records are returned to users) - but unfortunately, these services all run custom implementations that aren't part of any RFC standards.
http://aws.amazon.com/route53/faqs/#CloudFront_Zone_apex
http://www.dnsmadeeasy.com/aname-records/
https://support.dnsimple.com/articles/alias-record/

**Comment by gbinal** [comment]
Any luck with this?  

NASA currently has the most popular page right now and the link breaks b/c the `www` is required.  

![screen shot 2015-04-14 at 3 58 51 pm](https://cloud.githubusercontent.com/assets/633088/7146132/5abf0c56-e2bf-11e4-9395-b32fae57e1f8.png)

![screen shot 2015-04-14 at 3 59 21 pm](https://cloud.githubusercontent.com/assets/633088/7146138/5f31a06e-e2bf-11e4-89f3-4361bf25e311.png)

**Comment by danhammer** [comment]
The person who owns this responsibility is traveling, but the issue has been elevated to the NASA CTO (who is awesome and responsive).  I am hoping that this gets solved soon.  More updates soon.

**Comment by pavgup** [comment]
Rockstars.  All of you.  This make me unreasonably giddy.  I wish I could help more.

**Comment by danhammer** [comment]
@gbinal i tracked down the person who can make the change.  This is the response to the NASA CTO's request to fix the problem:

> This has come up before – we would need to put in a redirect server for nasa.gov. It wouldn't be ideal but better then whats there. It wasn't a priority so we didn't put in place. We can look at it putting it in after the redesign of the portal which should be rolled out over the next week. 

Any suggestions about how to keep the pressure on, so that this doesn't fall out of view?

**Comment by gbinal** [comment]
Offhand, I'd say give it until later this week when the portal rolls out and then check in and say, 'Okay, how about now?'.  

It's less than a matter of being burningly urgent as it as continuously bad.  Some X% of visitors open their browsers, type in `nasa.gov`, press enter, and it doesn't resolve.  Every. Day.  It's simply unfathomable to not address this.

**Comment by danhammer** [comment]
Fixed.  [nasa.gov](http://nasa.gov).

**Comment by rypan** [comment]
@danhammer excellent! looking forward to seeing it in action on https://analytics.usa.gov. 

i think this might be the first time in a long time that i haven't seen a NASA site in top 20....

**Comment by rossdakin** [comment]
🇺🇸👍🚀

**Comment by AbdessamadJamil** [comment]
![0cjycpuglt](https://cloud.githubusercontent.com/assets/14265553/10718413/0dcc3dee-7b6a-11e5-9ee1-966c85af7157.png)
