### ISSUE TITLE
Proper way to specify multiple ANALYTICS_REPORT_IDS

### ISSUE THREAD

**Issue by jlyon** [GSA/analytics.usa.gov#192]
I'm trying to aggregate reports for multiple Google Analytics properties.  I have tried a few combinations, but nothing has worked so far:

```
export ANALYTICS_REPORT_IDS=ga:9824111+ga:4095111
export ANALYTICS_REPORT_IDS=ga:9824111,ga:4095111
export ANALYTICS_REPORT_IDS=ga:9824111;ga:4095111
```

Each time I get this error:
```
ERROR AFTER QUERYING: Error: Invalid value 'ga:9824486+ga:4095255'. Values must match the following regular expression: 'ga:[0-9]+'
```

Is this possible? If so, what's the correct syntax? Thanks!

**Comment by konklone** [comment]
Hi @jlyon -- I don't think this is a supported operation at the moment. The [Google Analytics API documentation](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#ids) uses a plural field name, `ids`, but it describes the field as only accepting a single profile ID.

Client-side aggregation isn't out of the question, but it'd have to be designed thoughtfully so as not to complicate the code structure of `analytics-reporter`.

I'm closing this as (currently) out of scope for the project, but please do re-open if you'd like to discuss changing that.
