### ISSUE TITLE
Make sure metadata across sections are correct/consistent

### ISSUE THREAD

**Issue by leahbannon** [GSA/analytics.usa.gov#43]
The numbers on the page are currently defined as 
* people online right now
* visits
* visitors
* nothing (top sites)

**Comment by konklone** [comment]
- [ ] Label the Top Sites appropriately. The Live tab needs to indicate Pages and Active Users, the other tabs need to indicate Domains and Visitors. @rypan has a good mock for this:

![labels](https://cloud.githubusercontent.com/assets/4592/5745630/2a8659da-9bf8-11e4-89dc-b6da796cd74f.png)

**Comment by cew821** [comment]
Should add more descriptive text to describe the difference between pages / domains.

**Comment by leahbannon** [comment]
I think this is mostly resolved. Remaining issues with this are in #75
