### ISSUE TITLE
Create "Alpha" or "Beta" tag?

### ISSUE THREAD

**Issue by cew821** [GSA/analytics.usa.gov#50]
Should we have a way to indicate that the Analytics dashboard is in alpha, potentially linked to an anchor tag in the Github Readme that explains more about the project, what Alpha means, and how to contribute or provide feedback?

Like one of these?

![image](https://cloud.githubusercontent.com/assets/1237498/5746416/6e6bc220-9bfd-11e4-9a9e-f86390d43036.png)

**Comment by gbinal** [comment]
I def. like a 'beta' label somewhere on the page but also am +Fork Me in the top corner.  That said the fork me link could be in the footer, and thus be more demur.

**Comment by konklone** [comment]
Talked with @cew821 and @leahbannon in meatspace about this one. I personally think we're better off just presenting the site as a site we're launching that will constantly be evolving, rather than hedging on a "beta" label and looking to some milestone in the future. Similarly, I don't see this as "1.0" or "0.9", but just "the site".

**Comment by cew821** [comment]
As per conversation with the team, it seems like we have a rough consensus that we would like to add this. Based on the 18F definitions, I feel "beta" best matches our status.

**Comment by konklone** [comment]
:+1:

**Comment by cew821** [comment]
I will take a stab at adding this to the design.

**Comment by nsinai** [comment]
And for the record, @gbinal -- other than on developer-facing websites, "fork me" should be reserved for passive-aggressive nutrition websites only.

**Comment by gbinal** [comment]
:)  Great point.

**Comment by cew821** [comment]
So... i think we don't need this anymore :smile_cat:
