### ISSUE TITLE
add technology header back?

### ISSUE THREAD

**Issue by leahbannon** [GSA/analytics.usa.gov#71]
We need to clearly separate the technology section from the bar graph above it. People expressed some confusion about which section the 1.05 billion applies to. I'm open to suggestions better than "technology," but we need to add a header back.

**Comment by cew821** [comment]
I think this is related to the header spacing bug... the line should be below the time series chart.

![image](https://cloud.githubusercontent.com/assets/1237498/5766000/fed0c576-9ccb-11e4-973b-a3c7f8c94646.png)

**Comment by cew821** [comment]
This looks like it's resolved. Closing.

![image](https://cloud.githubusercontent.com/assets/1237498/5786601/de2c4738-9db5-11e4-9828-688aaa61ef62.png)

**Comment by leahbannon** [comment]
This might not be urgent pre-launch, but I don't think it's resolved. This issue came up a few times in ux testing, even with the line in the right place. People were confused about the lack of header for the technology section, which led them to think the 1.05 billion might relate to the graph above.

**Comment by konklone** [comment]
This was done.
