### ISSUE TITLE
Top 20 section: put some space between "Now" and "7 days"/"30 days" (2 separate pills)

### ISSUE THREAD

**Issue by leahbannon** [GSA/analytics.usa.gov#74]

**Comment by cew821** [comment]
What do you think of something like this?

![image](https://cloud.githubusercontent.com/assets/1237498/5810027/5ef06cd6-a005-11e4-9c7e-f7bf5999446b.png)

**Comment by konklone** [comment]
I really like that, assuming it survives being single-columned well.

If we went with this, we could remove the `Top 20` header above, and the `Pages` subheader below (and the `Domains` subheader on the other tabs), while leaving the single-sentence description.

**Comment by cew821** [comment]
I think we agreed that the new descriptive text @leahbannon added would solve this problem more elegantly. Please let me know if you would still like me to work on a fix here.
