### ISSUE TITLE
Mention that the DAP anonymizes IPs?

### ISSUE THREAD

**Issue by konklone** [GSA/analytics.usa.gov#83]
It might be nice to get out in front of a possible privacy backlash from certain corners when they realize that the US federal government has a giant Google Analytics account. The DAP does the very responsible thing of anonymizing IPs, and it might be worth a sentence or sentence fragment acknowledging it proactively.

**Comment by leahbannon** [comment]
👍👍👍 great idea -> I think it does more, too, like not collecting gender, etc? @timlowden

**Comment by konklone** [comment]
cc @tdlowden

**Comment by leahbannon** [comment]
fixed in #109

**Comment by MattiSG** [comment]
How exactly can you anonymize IPs before they are sent to Google? Are you hosting your own Google Analytics?

**Comment by konklone** [comment]
It's not before they are sent to Google -- we enable the flag in our client-side JS, and then [Google anonymizes the IP addresses before they are stored in their database](https://support.google.com/analytics/answer/2763052?hl=en). The IP address will be included with the network packets to Google no matter what we do, just because of internet routing.

**Comment by MattiSG** [comment]
Thanks for the answer!  :)
