### ISSUE TITLE
Realtime numbers for forecast.weather.gov/mapclick.php don't match

### ISSUE THREAD

**Issue by tdlowden** [GSA/analytics.usa.gov#84]
In the dashboard, we're seeing a tenth of the traffic we see in DAP itself. The following screenshots were taken seconds from each other.
![screen shot 2015-01-16 at 8 22 36 am](https://cloud.githubusercontent.com/assets/6556888/5776665/f26d18ba-9d58-11e4-8bff-573703a0c065.png)
![screen shot 2015-01-16 at 8 22 25 am](https://cloud.githubusercontent.com/assets/6556888/5776666/f2776f90-9d58-11e4-96c1-32bef787404b.png)

**Comment by tdlowden** [comment]
FYI the 1.3K NWS link is the one in question. The top one is weather.gov, which is rounding to 1.5 and is ok

**Comment by tdlowden** [comment]
This email from our vendor months ago that explains the issue:

"I took some time to look at this.

It appears the issue is dis-aggregation by page title.

The overview page shows top pages by URL.  10,000 for mapclick.php  

The Content page shows 2 dimensions,  URL + Page Title.  

The combination of mapclick.php + National Weather Service title is high enough to show up on the first page, but only 1400.  

But that URL has many other Page Titles sometimes.  If you filter on mapclick.php in the filter box, you'll see that the total is 10,000, same as overview.

And you'll also see all the other titles that URL can have -- they all involve specific locations."

**Comment by tdlowden** [comment]
So, the page title for forecast.weather.gov isn't always National Weather Service. That's the issue.

**Comment by konklone** [comment]
I think maybe we need to back up and talk about what this URL is. Is it a widget, embedded on a bunch of pages?

Unfortunately, with the way we currently manage data, we don't have a way of aggregating on page title without losing the page titles we're getting for all the other sites. 

I want to accurately represent the data, but, if the URL can "have many other page titles", it sounds to me like it's the page the widget is embedded *on* that should be counted for the traffic, not the widget itself.

**Comment by tdlowden** [comment]
It isn't a widget. The reason there are multiple page title is because the urls look like this:

http://forecast.weather.gov/MapClick.php?lat=38.90757960821344&lon=-77.01885611931368&site=all&smap=1#.VL5apEfF_1Y

and we stripped them of lat and lon. But, I have no idea why they have different page titles. Maybe it's by region or something?

**Comment by cew821** [comment]
Are we aggregating statistics by page title or URL? I had assumed URL, but if that's the case I don't understand why a link like http://forecast.weather.gov/MapClick.php?lat=38.90757960821344&lon=-77.01885611931368&site=all&smap=1#.VL5apEfF_1Y would be counted as http://forecast.weather.gov/MapClick.php

... or does GA only count the "non-parameter" stuff in the URL?

**Comment by konklone** [comment]
@cew821 I think this might have been mentioned in some other channel, but the issue is that DAP carved out a specific exception for forecast.weather.gov in their reporting, that chops off the latitude/longitude. Partly out of privacy concerns, partly for more effective aggregation. We don't have any evidence right now that Google chops off query string parameters as a general matter.

**Comment by konklone** [comment]
I think this is unlikely to change.
