### ISSUE TITLE
Verify that SNI is not required

### ISSUE THREAD

**Issue by konklone** [GSA/analytics.usa.gov#88]
Sadly, until Windows XP support is a non-issue, we have to support HTTPS without requiring Server Name Indication. This costs us extra for hosting, and requires manually increasing our limit with Amazon. I've set this up for `analytics.usa.gov`. It'd be nice to drop this cost down the line. In the meantime, we should verify, using Python 2 or a Windows XP VM, that the site is accessible to legacy clients. 

Hopefully there's a website in the government somewhere that tracks Windows XP usage so we can know when it's all right to start requiring SNI and to drop our costs.

**Comment by alex** [comment]
`openssl s_client -connect analytics.usa.gov:443 | openssl x509 -noout -text` shows a cert that has a correct SAN for `analytics.usa.gov` and `www.analytics.usa.gov`.

(`openssl s_client` does not use the SNI extension by default, `-servername` is requiredfor that)

**Comment by konklone** [comment]
OK, and I just confirmed that `urllib2` in Python 2.7.8 successfully can access `https://analytics.usa.gov`. (And confirmed that it fails on `https://www.mnot.net`, which [intentionally requires SNI](https://www.mnot.net/blog/2014/05/09/if_you_can_read_this_youre_sniing).)

Note: Python 2.7.9 [supports SNI](https://www.mnot.net/blog/2014/12/27/python_2_and_tls_sni).

**Comment by konklone** [comment]
Thanks, @alex!
