### ISSUE TITLE
OpenGraph metadata and Twitter cards

### ISSUE THREAD

**Issue by konklone** [GSA/analytics.usa.gov#94]
Gotta get the metadata in order to have nice title/description text appear when shared on Twitter and Facebook. This also means getting the domain approved for Twitter cards, which I should be able to do.

**Comment by cew821** [comment]
Does this look ok?

![image](https://cloud.githubusercontent.com/assets/1237498/5789796/8b3fd7e8-9e36-11e4-9db8-ab7cb4b2f092.png)

**Comment by konklone** [comment]
The framing is right -- but I'll grab a similar one from my work Macbook, which has a very high density display. Facebook's minimum is 600x315, and recommended is 1200x630.
